let Memesdata={
    "data":{
        "memes":[
            {
                "url":"images/meme1.jpg"
            },
            {
                "url":"images/meme2.jpg"
            },{
                "url":"images/meme3.jpg"
            },{
                "url":"images/meme4.jpg"
            },{
                "url":"images/meme5.jpg"
            },{
                "url":"images/meme6.jpg"
            },{
                "url":"images/meme7.jpg"
            },{
                "url":"images/meme8.jpg"
            },{
                "url":"images/meme9.jpg"
            },{
                "url":"images/meme10.jpg"
            },{
                "url":"images/meme11.jpg"
            },{
                "url":"images/meme1.jpg"
            },{
                "url":"images/meme12.jpg"
            },{
                "url":"images/meme13.jpg"
            },{
                "url":"images/meme14.jpg"
            },{
                "url":"images/meme15.jpg"
            },{
                "url":"images/meme16.jpg"
            },{
                "url":"images/meme17.jpg"
            },{
                "url":"images/meme18.jpg"
            },{
                "url":"images/meme19.jpg"
            },{
                "url":"images/meme20.jpg"
            },{
                "url":"images/meme21.jpg"
            },{
                "url":"images/meme22.jpg"
            },{
                "url":"images/meme23.jpg"
            },{
                "url":"images/meme24.jpg"
            },{
                "url":"images/meme25.jpg"
            },{
                "url":"images/meme26.jpg"
            },{
                "url":"images/meme27.jpg"
            },{
                "url":"images/meme28.jpg"
            },{
                "url":"images/meme29.jpg"
            },{
                "url":"images/meme30.jpg"
            }
        ]
    }
}

export default Memesdata